stages:
  load_data:                  #name of the first stage
    cmd: python src/load_data.py --config=params.yaml
    deps: 
    - src/get_data.py
    - src/load_data.py
    - data_given/iris-flower-species.csv
    outs:
    - data/raw/iris-flower-species.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/iris-flower-species.csv
    outs:
    - data/processed/train_iris.csv
    - data/processed/test_iris.csv 