base:
  project: iris-flower-species-project
  random_state: 42
  target_col: Species

data_source:
  s3_source: data_given/iris-flower-species.csv

load_data:
  raw_dataset_csv: data/raw/iris-flower-species.csv

split_data:
  train_path: data/processed/train_iris.csv
  test_path: data/processed/test_iris.csv
  test_size: 0.2

estimators:
  RandomForestClassifier:
    params:
      n_estimators: 20, 
      n_features: 20, 
      n_informative: 15,
      n_redundant: 5

model_dir: save_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib



# outs:
# - md5: 778ae91888970b3b066b0e71d59fd610
#   size: 3404
#   path: iris-flower-species.csv